### ISSUE TITLE
Twitter threads

### ISSUE THREAD

**Issue by ashishbhateja** [DominikPieper/obsidian-ReadItLater#19] opened 2021-11-03 05:31 UTC
Is there a way to save twitter threads?

**Comment by DominikPieper** [comment] 2021-11-03 09:34
Right now there's no such feature

**Comment by mvrai** [comment] 2023-05-22 01:55
Having this feature would be great! 
There is a  plugin that can handle it, but it does require a twitter bearer token: 
https://github.com/kbravh/obsidian-tweet-to-markdown

Could @DominikPieper kindly take a moment to look into this and share his input?

**Comment by lukacovicadam** [comment] 2023-06-06 18:10
Closing as duplicate of #91

**Closed by lukacovicadam** 2023-06-06 18:10 UTC
Labels: duplicate
